### PR TITLE
Script requires PowerShell 3.0

### PR DESCRIPTION
**Pull request by crossan007**

### CODE REVIEW

**Comment by crossan007** [comment]
@spjeff   Don't merge this yet - I'm still troubleshooting.   It seems that PowerShell on Server2008R2 does not have the ```Get-CimInstance``` cmdlet

**Comment by crossan007** [comment]
https://powershell.org/2013/04/10/get-ciminstance-from-powershell-2-0/

**Comment by crossan007** [comment]
Add a #requires -Version 3.0 tag so that the script will give an informative error if running on unsupported platform.

https://msdn.microsoft.com/en-us/powershell/reference/5.1/microsoft.powershell.core/about/about_requires

**Review by spjeff — APPROVED** [review]
Looks good.  Thanks!

**Pull request merged**
