### PR TITLE
Update SPBestWarmUp.ps1

### PR DESCRIPTION
**Pull request by aschulz01**
1. Supporting Extended SharePoint WebApplications
2. warmup ADFS environments (calling the trusted identity provider url) 
     (the adfs server itself should warmed up in the custum url section)

### CODE REVIEW

**Comment by spjeff** [comment]
Hey Andreas!

Excellent suggestion.   I updated the code and committed to master.   Would you please download v2.2.5 and run a few tests?

https://github.com/spjeff/spbestwarmup/blob/master/SPBestWarmUp.ps1

**Comment by aschulz01** [comment]
Hi Jeff,

$wa is no longer defined while iterating through the sitecollections.

Best regards,
Andreas

[cid:image001.png@01D23464.C7404E60]

**Comment by spjeff** [comment]
Please try now.   Made a fresh new commit using $wa.AlternateUrls to loop web apps outside and loop the various AAM inside for that parent web app.

**Comment by aschulz01** [comment]
Hi Jeff,

yes, this works ☺ thank you.

I have a other hint:
On x64 Systems the Get-Process return column “PM(K)” overflows on large working sets.
See:
[cid:image001.png@01D2346D.8A086010]
So wrong sum values are shown.
[cid:image004.jpg@01D2346E.50504350]

Solution working on x64:
$mb = [Math]::Round((Get-Process W3WP -ErrorAction SilentlyContinue | Select-Object workingset64 | Measure-Object workingset64 -Sum).Sum/1MB)

Best regards
Andreas

**Comment by spjeff** [comment]
Awesome!  =)

Yeah, everybody has X64 for SharePoint so that's a given.

Just updated that line, committed to master, and updated download ZIP too.

**Comment by spjeff** [comment]
ZIP download pages are now updated.

https://github.com/spjeff/spbestwarmup/releases

https://spbestwarmup.codeplex.com/releases/view/106685

**Pull request closed without merging**
